controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: false

    diff_drive_controller:
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_state_broadcaster:
  ros__parameters:
    use_sim_time: false

diff_drive_controller:
  ros__parameters:
    left_wheel_names: ["front_left_motor", "back_left_motor"]
    right_wheel_names: ["front_right_motor", "back_right_motor"]

    wheel_separation: 0.44
    wheel_radius: 0.13

    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    odom_frame_id: odom
    base_frame_id: base_link
    pose_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
    twist_covariance_diagonal: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]

    position_feedback: true
    open_loop: false
    enable_odom_tf: false

    cmd_vel_timeout: 0.25 # seconds
    publish_limited_velocity: true
    velocity_rolling_window_size: 10

    linear.x.max_velocity: 1.5
    linear.x.min_velocity: -1.5
    linear.x.max_acceleration: 2.5
    linear.x.max_deceleration: -2.5
    linear.x.max_acceleration_reverse: -2.5
    linear.x.max_deceleration_reverse: 2.5
    linear.x.max_jerk: .NAN
    linear.x.min_jerk: .NAN

    angular.z.max_velocity: 12.0
    angular.z.min_velocity: -12.0
    angular.z.max_acceleration: 15.0
    angular.z.max_deceleration: -15.0
    angular.z.max_acceleration_reverse: -15.0
    angular.z.max_deceleration_reverse: 15.0
    angular.z.max_jerk: .NAN
    angular.z.min_jerk: .NAN
